import type { Persona } from "../../lib/types";

export const EMPTY_PERSONA: Persona = {
  name: "", age: "", role: "Étudiant", type: "", photo: "",
  occupation: "", studyLevel: "", program: "", yearOfStudy: "", bio: "", personality: "",
  maritalStatus: "", children: "", nationality: "", languages: "", hobbies: "", sports: "",
  musicTaste: "", readingHabits: "", socialStyle: "", values: "", fears: "", deepMotivations: "",
  stressLevel: "", stressManagement: "", sleepSchedule: "", diet: "", healthConsiderations: "",
  volunteerWork: "", travelHistory: "", roleModel: "", lifePhilosophy: "", weekendActivities: "",
  personalSocialMedia: "", monthlyBudget: "", dreamVacation: "", petOrNot: "",
  politicalEngagement: "", religiousViews: "", currentReads: "", favoriteSeries: "",
  introExtrovert: "", morningOrNight: "", bigLifeEvent: "",
  campus: "", neighborhood: "", housing: "", transportation: "",
  arriveTime: "", departTime: "", workSchedule: "", favoriteSpots: "",
  studentId: "", enrollmentDate: "", scholarshipStatus: "", partTimeJob: "",
  whyKeyce: "", previousSchool: "", parentsProfession: "", siblings: "", dreamJob: "",
  internshipExperience: "", relationWithTeachers: "", bestSubject: "", worstSubject: "",
  yearGoal: "", afterSchoolPlan: "", financialAid: "", dailyBudget: "",
  learningStyle: "", studyHabits: "", extracurricular: "", careerGoals: "",
  academicStrengths: "", academicWeaknesses: "", groupOrSolo: "", examStress: "", repeatYear: "",
  position: "", department: "", yearsAtKeyce: "", contractType: "", teachingHours: "", subjectsTaught: "",
  teachingStyle: "", classSize: "", assessmentMethods: "", previousCareer: "", whyTeaching: "",
  teachingPhilosophy: "", proudestAchievement: "", biggestChallenge: "", mentors: "",
  workLifeBalance: "", hopeForStudents: "", careerPlans: "", jobSatisfaction: "", prepTime: "",
  teachingAtOtherSchools: "", continuingEducation: "", unionMembership: "",
  relationWithStudents: "", relationWithAdmin: "", salaryRange: "",
  responsibleFor: "", teamSize: "", keyProcesses: "", managementStyle: "",
  decisionAuthority: "", careerPath: "", teamRelations: "", remoteWork: "",
  emailsPerDay: "", meetingsPerWeek: "", reportTo: "", externalRelations: "",
  biggestChallengeAdmin: "", proudestAchievementAdmin: "", workLifeBalanceAdmin: "",
  regulatoryPressure: "", conflictManagement: "", adminSatisfaction: "",
  primarySystemNeeds: "", frequentTasks: "", timeSpentOnSystem: "", systemUsage: "",
  techSavvy: "", digitalTools: "", devices: "", apps: "",
  privacyConcerns: "", techFrustrations: "", learnNewTechHow: "",
  goals: "", frustrations: "", needs: "", quote: "",
  idealFeature: "", dealBreaker: "", onboardingExpectation: ""
};

export const PERSONA_TEMPLATES: Record<string, Partial<Persona>> = {
  "etudiant-bts": {
    role: "Étudiant", type: "L'étudiant connecté", occupation: "Étudiant BTS",
    studyLevel: "Bac+2", program: "BTS MCO (Management Commercial Opérationnel)", yearOfStudy: "2ème année",
    neighborhood: "Jean-Jaurès", housing: "Studio étudiant - Résidence Studéa Jean Jaurès",
    transportation: "Métro Ligne B (Jean-Jaurès → Jeanne d'Arc)",
    arriveTime: "8h15", departTime: "17h30", workSchedule: "8h30-17h30 (lundi au vendredi)",
    favoriteSpots: "Bibliothèque François Mitterrand, Espace Coworking Wellio, Café Bibent",
    studentId: "KEY2024-MCO-0156", enrollmentDate: "Septembre 2023", scholarshipStatus: "Boursier échelon 4",
    partTimeJob: "Vendeur chez Décathlon Wilson (15h/semaine)",
    bio: "Lucas Martin, 21 ans, étudiant en 2ème année de BTS MCO. Originaire de Colomiers, il habite un studio près de Jean-Jaurès. Entre ses cours, son job étudiant et sa vie sociale, il jongle avec de nombreux emplois du temps. Il trouve Ypareo peu ergonomique et difficile d'accès sur mobile.",
    personality: "Dynamique, organisé, tech-savvy, sociable, impatient face aux interfaces complexes",
    maritalStatus: "Célibataire", children: "Aucun", nationality: "Française",
    languages: "Français (natif), Anglais (B2), Espagnol (A2 scolaire)",
    hobbies: "Gaming (FIFA, Valorant), Photographie urbaine, Cuisine autodidacte, Podcasts entrepreneuriat",
    sports: "Football (équipe campus), Running 5km, Fitness 2x/semaine",
    musicTaste: "Hip-hop français (Ninho, SCH, Orelsan), R&B, Electronic pour travailler",
    readingHabits: "Quasi exclusivement podcasts et YouTube. Lit 1-2 livres/an (business).",
    socialStyle: "Extraverti modéré - aime les groupes mais a besoin de moments seul",
    values: "Ambition, authenticité, loyauté, liberté financière",
    fears: "Échouer les examens et décevoir ses parents, ne pas trouver de travail",
    deepMotivations: "Prouver qu'il peut réussir malgré un contexte modeste, offrir une vie meilleure à sa famille",
    stressLevel: "Élevé en examens (7/10), modéré le reste (4/10)",
    stressManagement: "Gaming pour décompresser, appels avec sa mère, sorties amis, musique forte",
    sleepSchedule: "Couche-tard (minuit-1h), lever difficile (7h15). Manque chronique de sommeil.",
    diet: "Mange souvent au campus ou snacks rapides. Cuisine le week-end. Budget alimentaire serré.",
    healthConsiderations: "Légères douleurs au dos (posture ordi). Lunettes. Anxiété ponctuelle.",
    volunteerWork: "Président BDE campus. Tuteur bénévole lycéens en difficulté.",
    travelHistory: "Séjour linguistique Londres (lycée). Vacances famille Maroc. Rêve d'Asie.",
    roleModel: "Elon Musk (ambition), Gary Vaynerchuk (entrepreneuriat), son oncle entrepreneur",
    lifePhilosophy: "Travaille dur en silence, laisse le succès faire le bruit",
    weekendActivities: "Sorties amis (bars Jean-Jaurès), football dimanche, courses et cuisine, gaming vendredi",
    personalSocialMedia: "Instagram (450 followers), TikTok (consommateur), LinkedIn (en construction)",
    monthlyBudget: "850€ (APL 200€ + bourse 450€ + job 200€). Loyer 450€.",
    dreamVacation: "Road trip Californie + visite Silicon Valley",
    petOrNot: "Voudrait un chien mais studio interdit",
    introExtrovert: "Extraverti (7/10)", morningOrNight: "Noctambule (couche après minuit)",
    bigLifeEvent: "Perte de son père à 15 ans - l'a rendu très autonome et mature précocement",
    whyKeyce: "Réputation formation MCO, coût accessible, campus centre-ville",
    previousSchool: "Lycée Pierre de Fermat (Toulouse) - Bac STMG mention Bien",
    parentsProfession: "Mère aide-soignante (CHU Purpan), père décédé",
    siblings: "2 sœurs cadettes (17 et 14 ans)",
    dreamJob: "Créer sa startup e-commerce sportif, ou responsable marketing Nike/Adidas",
    internshipExperience: "Stage 6 semaines Décathlon (gestion rayon). Actuellement alternance vendeur 15h/sem.",
    relationWithTeachers: "Bonne. Apprécie les profs qui viennent du terrain.",
    bestSubject: "Management commercial, Marketing digital, Gestion de projet",
    worstSubject: "Comptabilité, Droit commercial, Anglais écrit",
    yearGoal: "Obtenir BTS avec mention, décrocher alternance pour Bachelor",
    afterSchoolPlan: "Bachelor Marketing Digital en alternance",
    financialAid: "Bourse CROUS échelon 4 (4500€/an), APL 200€/mois",
    dailyBudget: "~15€/jour (repas campus 5€, transport 2€)",
    learningStyle: "Visuel et pratique - préfère les vidéos et cas concrets",
    studyHabits: "Travail en groupe, révisions de dernière minute, utilise YouTube",
    extracurricular: "Président BDE, équipe football, tuteur bénévole",
    careerGoals: "Responsable magasin → Responsable marketing → Créer sa propre entreprise retail",
    academicStrengths: "Présentation orale, travaux pratiques, projets groupe",
    academicWeaknesses: "Manque de rigueur à l'écrit, gestion du temps long terme",
    groupOrSolo: "Fortement groupe (8/10)", examStress: "Stress élevé mais canalisé",
    repeatYear: "Non - première tentative",
    primarySystemNeeds: "Consultation rapide emploi du temps\nAccès aux notes et résultats\nSignature émargement\nTéléchargement documents\nSuivi des absences",
    frequentTasks: "Consulter l'emploi du temps (2-3x/jour)\nSigner émargement (chaque cours)\nVérifier les notes (1-2x/semaine)",
    timeSpentOnSystem: "10-15 min/jour, 5-8 connexions", systemUsage: "90% mobile",
    devices: "iPhone 13, MacBook Air M1, iPad (occasionnel)",
    apps: "Instagram, TikTok, Notion, Discord, Spotify",
    techSavvy: "Expert - Early adopter, très à l'aise avec toute technologie",
    digitalTools: "Notion, Google Calendar, Discord, Slack, Trello",
    privacyConcerns: "Peu préoccupé - partage volontiers ses données si service utile",
    techFrustrations: "Apps lentes, interfaces non intuitives, trop d'étapes pour action simple",
    learnNewTechHow: "YouTube tutorials + trial & error, jamais les notices",
    goals: "Accéder rapidement à mon emploi du temps depuis mon téléphone\nRecevoir des notifications pour les changements\nSigner l'émargement sans bug\nTélécharger mes documents en 2 clics\nVoir mes notes dès publication",
    frustrations: "Ypareo plante souvent sur mobile\nInterface datée et peu intuitive\nPas de notifications push\nÉmargement instable\nDocuments difficiles à trouver",
    needs: "Application mobile native et fluide\nNotifications push intelligentes\nÉmargement par QR code\nTableau de bord centralisé\nMode hors ligne emploi du temps",
    quote: "Je perds 5 minutes à chaque fois que je veux juste voir à quelle heure j'ai cours demain. J'aimerais une app aussi simple que mon app de banque !",
    idealFeature: "Widget emploi du temps sur l'écran d'accueil iOS et notifications instantanées",
    dealBreaker: "Pas d'application mobile. Plus de 3 clics pour une action fréquente.",
    onboardingExpectation: "Tutoriel interactif à la première connexion. Aide contextuelle dans l'app."
  },
  "enseignant": {
    role: "Enseignant", type: "L'enseignante multi-campus", occupation: "Enseignante / Formatrice",
    studyLevel: "Master 2 Commerce International", program: "N/A - Personnel enseignant",
    neighborhood: "Compans-Caffarelli", housing: "Appartement propriétaire - Rue Riquet (T3, 68m²)",
    transportation: "Voiture (déplacements inter-campus) + Métro Ligne B",
    arriveTime: "8h00", departTime: "19h00", workSchedule: "Horaires variables - 24h cours/semaine",
    favoriteSpots: "Marché Victor Hugo, Bibliothèque Universitaire, Co-working La Cantine",
    position: "Formatrice en Marketing et Commerce", department: "Pôle Commerce / Marketing", yearsAtKeyce: "6 ans",
    contractType: "CDI temps plein", teachingHours: "24h/semaine (+ 10h préparation/correction)",
    subjectsTaught: "Marketing digital, E-commerce, Stratégie commerciale, Négociation",
    bio: "Sophie Mercier, 38 ans, enseignante en marketing et commerce depuis 6 ans. Ancienne responsable marketing en entreprise 8 ans. Enseigne à 8 classes (~180 étudiants). Trouve le système actuel trop fragmenté.",
    personality: "Pédagogue, organisée, exigeante mais bienveillante, frustrée par les outils obsolètes",
    maritalStatus: "Mariée depuis 8 ans", children: "2 enfants (Emma 6 ans, Théo 4 ans)",
    nationality: "Française (parents algériens)",
    languages: "Français (natif), Anglais (C1 - vécu 2 ans à Londres), Arabe (compréhension)",
    hobbies: "Yoga (3x/semaine), Cuisine méditerranéenne, Jardinage (balcon), Déco intérieure",
    sports: "Yoga Vinyasa, Randonnée en famille (Pyrénées), Natation ponctuelle",
    musicTaste: "Jazz français, Chansons françaises classiques, World Music, Podcasts culture G",
    readingHabits: "15-20 livres/an. Romans, essais pédagogiques, podcasts France Culture.",
    socialStyle: "Ambivert - extravertie au travail, introvertie à la maison",
    values: "Équité, transmission, exigence bienveillante, travail bien fait, famille avant tout",
    fears: "Perdre le lien avec ses étudiants, épuisement professionnel, être dépassée technologiquement",
    deepMotivations: "Voir ses étudiants réussir professionnellement, laisser une empreinte positive",
    stressLevel: "Élevé en examens (8/10), modéré le reste (5/10)",
    stressManagement: "Yoga quotidien (indispensable), jardinage, discussions avec mari, lecture",
    sleepSchedule: "Couche-tôt quand possible (22h30), souvent 23h30 en période chargée. Lever 6h30.",
    healthConsiderations: "Tendinite épaule droite (trop d'ordi). Migraines lors des pics de stress.",
    volunteerWork: "Marraine dans programme 'Femmes & Entreprises'. Ex-membre CA association culturelle.",
    travelHistory: "2 ans expatriée Londres. Voyages pro Bruxelles, Barcelone. Famille en Algérie.",
    roleModel: "Ken Robinson (pédagogie créative), Christine Lagarde, ses parents (résilience)",
    lifePhilosophy: "Enseigner ce n'est pas remplir un vase, c'est allumer un feu (Plutarque)",
    weekendActivities: "Activités famille, marché samedi matin, dîner amis, préparation cours dimanche",
    personalSocialMedia: "LinkedIn (1200 contacts, profil soigné), Instagram privé, Pinterest",
    monthlyBudget: "Famille 2 revenus confortables. Propriétaires. Budget vacances 3000€/an.",
    introExtrovert: "Ambivert (5/10)", morningOrNight: "Matin (6h30 lever)",
    bigLifeEvent: "Reconversion professionnelle à 32 ans (du marketing à l'enseignement)",
    previousCareer: "8 ans marketing B2B : Chef produit (2 ans), Resp. marketing Fnac (3 ans), Consultante (3 ans)",
    whyTeaching: "Lassitude du corporate, envie de transmettre, flexibilité famille",
    teachingPhilosophy: "Pédagogie active et expérientielle. Chaque cours doit avoir un ancrage concret.",
    proudestAchievement: "3 anciens étudiants créent leur startup. Une étudiante décroche CDI chez LVMH.",
    biggestChallenge: "Maintenir cours à jour dans domaine qui évolue tous les 6 mois. Surcharge administrative.",
    workLifeBalance: "Difficile avec 2 jeunes enfants + double campus. Équilibre fragile mais possible.",
    hopeForStudents: "Qu'ils trouvent un métier qui leur plait. Qu'ils aient confiance en leurs capacités.",
    jobSatisfaction: "7/10 - Passion intacte pour la pédagogie. Frustration face au temps perdu en admin.",
    prepTime: "2-3h/heure nouveau cours, 30min cours rodé. Corrections: 1h30 pour 25 copies.",
    teachingStyle: "Pédagogie active avec études de cas, travaux de groupe, interventions professionnels",
    classSize: "Classes de 20-30 étudiants",
    assessmentMethods: "Contrôles continus, projets de groupe, soutenances orales, examens finaux",
    primarySystemNeeds: "Gestion des émargements\nDépôt de documents et supports de cours\nSaisie et publication des notes\nConsultation de l'emploi du temps\nCommunication avec les étudiants",
    frequentTasks: "Émarger les cours (3-4x/jour)\nDéposer supports (2-3x/semaine)\nSaisir notes (hebdomadaire)",
    timeSpentOnSystem: "45-60 min/jour sur tâches admin", systemUsage: "Ordinateur portable (70%), tablette en classe (20%)",
    devices: "MacBook Pro 14 pouces, iPad Pro (émargement classe), iPhone 12",
    apps: "Outlook, Teams, OneNote, Google Drive, Slack, LinkedIn",
    techSavvy: "Avancé - Utilise régulièrement des outils numériques mais attend qu'ils soient intuitifs",
    digitalTools: "Moodle, Google Workspace, Canva, Trello, Zoom",
    goals: "Émarger rapidement mes cours sans bugs\nDéposer et organiser facilement mes supports\nSaisir notes avec import Excel\nAvoir vue claire emploi du temps avec salles",
    frustrations: "Interface complexe avec trop de clics\nÉmargement qui plante régulièrement\nPas d'import notes par tableur\nDifficile de retrouver les anciens documents",
    needs: "Interface simplifiée et moderne\nÉmargement fiable mobile/tablette\nUpload groupé avec tags\nImport/export Excel pour les notes",
    quote: "Je passe 1h par jour sur des tâches administratives basiques. C'est 5h par semaine que je pourrais consacrer à améliorer mes cours !",
    idealFeature: "Module 'Cours du jour' : liste présence + supports + émargement en un seul écran",
    dealBreaker: "Perte de données (notes, émargements). Système qui force à ressaisir ce déjà saisi.",
    onboardingExpectation: "Demi-journée de formation en groupe + documentation PDF + support téléphonique"
  },
  "admin": {
    role: "Administration", type: "La responsable pédagogique", occupation: "Responsable Pédagogique et Administrative",
    studyLevel: "Master 2 Management des Organisations",
    neighborhood: "Capitole", housing: "Maison propriétaire - Quartier Saint-Agne (4 pièces, jardin)",
    transportation: "Voiture + Parking campus",
    arriveTime: "7h45", departTime: "18h30", workSchedule: "8h-18h (lundi-vendredi) + samedi 1x/mois",
    favoriteSpots: "Campus, Jardin des Plantes (pause déjeuner)",
    position: "Responsable Pédagogique BTS/Bachelor", department: "Direction Pédagogique et Vie Scolaire",
    yearsAtKeyce: "12 ans", contractType: "CDI Cadre",
    bio: "Marie Dubois, 45 ans, responsable pédagogique depuis 12 ans. Supervise 4 formations (240 étudiants, 18 enseignants). Gère inscriptions, planification, absences, examens, bulletins, stages. Utilise Ypareo 4-6h/jour.",
    personality: "Rigoureuse, multitâche, diplomate, résistante au stress, perfectionniste",
    maritalStatus: "Divorcée depuis 4 ans - garde alternée", children: "2 enfants (Pierre 16 ans, Lucie 13 ans)",
    nationality: "Française",
    languages: "Français (natif), Anglais (B1 - fonctionnel)",
    hobbies: "Jardinage (passion), Aquarelle (cours soir 1x/semaine), Cuisine du terroir, Jeux de société",
    sports: "Marche nordique (2x/semaine, Bords de Garonne), Natation (mercredi midi)",
    musicTaste: "Variété française 80-90, Jazz, Radio Classique pendant travail concentré",
    readingHabits: "10-12 livres/an. Romans policiers (Fred Vargas), biographies, management.",
    socialStyle: "Introvertie au fond mais parfaitement adaptée aux contextes sociaux professionnels",
    values: "Intégrité, rigueur, service aux autres, équité, travail bien fait même sans reconnaissance",
    fears: "Commettre une erreur administrative grave (légal, certification), perdre le contrôle",
    deepMotivations: "Être le pilier invisible sur lequel tout repose. Fierté de voir des centaines d'étudiants diplômés.",
    stressLevel: "Structurellement élevé (6/10 quotidien, 9/10 en examens/inscriptions)",
    stressManagement: "Jardinage week-end (thérapeutique), marche nordique, organisation ultra-rigoureuse",
    sleepSchedule: "Couche tôt (22h) mais réveils nocturnes fréquents en stress. Lever 6h30.",
    healthConsiderations: "Troubles du sommeil chroniques. Tendinite poignet droit (Excel toute la journée).",
    volunteerWork: "Ex-présidente association parents d'élèves. Bénévole banque alimentaire 1 dimanche/mois.",
    travelHistory: "Rarement. Week-end Barcelone (annuel), vacances Bretagne famille. Rêve d'Islande.",
    roleModel: "Sa directrice pédagogique (retraitée, bienveillance). Angela Merkel (rigueur). Sa mère (institutrice).",
    lifePhilosophy: "Le travail bien fait est sa propre récompense",
    weekendActivities: "Jardin (samedi), courses marché, activités enfants, aquarelle (dimanche), préparation semaine",
    personalSocialMedia: "LinkedIn (600 contacts, pro), Facebook (famille uniquement)",
    monthlyBudget: "Salaire cadre (~2800€ net). Propriétaire. Budget contraint depuis divorce.",
    introExtrovert: "Introvertie (3/10 extraverti)", morningOrNight: "Matin (7h45 au campus quand personne)",
    bigLifeEvent: "Divorce 2020 (COVID+séparation simultanés). Révélatrice de résilience et autonomie.",
    managementStyle: "Bienveillant-exigeant - écoute + rigueur",
    decisionAuthority: "Autonomie totale gestion pédagogique. Consulte directeur pour financier, recrutements, sanctions graves.",
    careerPath: "Assistante pédagogique (2012) → Coordinatrice BTS (2015) → Responsable Pédagogique (2018)",
    teamRelations: "Très bonne avec 3 assistantes. Complexe avec certains enseignants (résistance au changement).",
    emailsPerDay: "80-120 emails/jour. Tri et réponse = 1h30/jour minimum.",
    meetingsPerWeek: "8-12 réunions/semaine",
    responsibleFor: "Coordination pédagogique 4 formations (240 étudiants)\nGestion emplois du temps\nSupervision 18 enseignants\nSuivi absences et sanctions\nOrganisation examens",
    teamSize: "3 assistantes pédagogiques + 18 enseignants",
    keyProcesses: "Inscriptions et réinscriptions\nCréation emplois du temps\nSuivi absences\nOrganisation examens/jurys\nÉdition bulletins et attestations\nGestion stages\nReporting direction et organismes",
    primarySystemNeeds: "Gestion complète du cycle de vie étudiant\nCréation et gestion des emplois du temps\nSuivi des absences avec alertes automatiques\nÉdition de documents administratifs\nGénération rapports et statistiques",
    frequentTasks: "Vérification absences (30 min/jour)\nRéponse attestations (10-15/jour)\nGestion modifications EDT (quotidien)\nTraitement justificatifs (20-30/semaine)",
    timeSpentOnSystem: "4 à 6 heures par jour", systemUsage: "100% ordinateur (double écran indispensable)",
    devices: "PC Dell double écran 24 pouces, iPhone 11",
    apps: "Outlook, Excel, Teams, Adobe Acrobat, outils signature électronique",
    techSavvy: "Avancé - Expert des systèmes de gestion mais frustrée par les limitations",
    digitalTools: "Excel (expert), Ypareo (expert), Outlook, Teams, outils de reporting",
    goals: "Automatiser les tâches répétitives\nVue d'ensemble temps réel sur tous les étudiants\nGénérer rapidement des rapports\nGérer emplois du temps avec détection conflits\nSuivre absences avec alertes automatiques",
    frustrations: "Interface vieillissante et lente\nPas de génération automatique de documents\nManque de tableaux de bord visuels\nPas d'alertes pour seuils critiques\nGestion EDT sans détection conflits",
    needs: "Tableau de bord KPI temps réel\nGénération automatique documents\nSystème d'alertes intelligent\nGestion EDT drag & drop avec conflits détectés\nWorkflow de validation\nModule reporting avancé",
    quote: "J'ai l'impression de passer 60% de mon temps à faire des tâches répétitives qui devraient être automatisées. On a besoin d'un vrai système moderne.",
    idealFeature: "Tableau de bord matinal 'Alertes du jour' : absences anormales, documents en attente, conflits EDT",
    dealBreaker: "Système qui perd des données ou ne trace pas les actions (RGPD). Pas d'export Excel.",
    onboardingExpectation: "Formation complète 2 jours + manuel détaillé + hotline 6 mois + transition parallèle"
  }
};

const SCORED_FIELDS: (keyof Persona)[] = [
  "name", "age", "role", "type", "bio", "personality",
  "maritalStatus", "children", "nationality", "languages",
  "hobbies", "values", "fears", "deepMotivations", "stressLevel",
  "lifePhilosophy", "introExtrovert", "morningOrNight", "bigLifeEvent",
  "campus", "neighborhood", "housing", "transportation", "workSchedule",
  "techSavvy", "devices", "apps", "digitalTools",
  "primarySystemNeeds", "frequentTasks", "timeSpentOnSystem", "systemUsage",
  "goals", "frustrations", "needs", "quote"
];

const ROLE_FIELDS: Record<string, (keyof Persona)[]> = {
  "Étudiant": ["studentId", "studyLevel", "program", "learningStyle", "careerGoals", "whyKeyce"],
  "Enseignant": ["position", "department", "teachingStyle", "previousCareer", "teachingPhilosophy"],
  "Administration": ["position", "department", "responsibleFor", "managementStyle", "keyProcesses"]
};

export function computeCompletion(persona: Persona): number {
  const roleSpecific = ROLE_FIELDS[persona.role] ?? [];
  const allFields = [...SCORED_FIELDS, ...roleSpecific];
  const filled = allFields.filter(f => (persona[f] as string)?.trim().length > 0).length;
  return Math.round((filled / allFields.length) * 100);
}
