import type { School } from "./schoolStore";

export interface SchoolTemplate {
  id: string;
  label: string;
  emoji: string;
  description: string;
  data: Partial<School>;
}

export const SCHOOL_TEMPLATES: SchoolTemplate[] = [
  {
    id: "universite-publique",
    label: "Université Publique",
    emoji: "🏛️",
    description: "Grande université avec plusieurs campus, milliers d'étudiants, recherche active",
    data: {
      type: "Université publique",
      country: "France",
      totalStudents: "15000",
      totalTeachers: "800",
      totalAdminStaff: "400",
      campusCount: "3",
      departments: "Sciences, Lettres, Droit, Médecine, Économie, Informatique",
      degreeLevels: "Licence, Master, Doctorat",
      teachingModality: "Présentiel majoritaire + cours en amphithéâtre + TD/TP",
      gradingSystem: "Notes /20, compensations entre UE, crédits ECTS",
      teachingLanguages: "Français (principal), Anglais (certains masters)",
      alternancePercent: "10%",
      internationalPercent: "15%",
      internshipRequired: "Oui (stage obligatoire en Master)",
      researchActivity: "Très active - laboratoires, publications, thèses",
      currentSoftware: "Apogée + Moodle + ENT maison",
      currentPainPoints: "Système hérité complexe, inscriptions laborieuses, pas de mobile, lenteur aux examens",
      attendanceMethod: "Feuilles papier ou absence de contrôle en amphi",
      gradeManagement: "Apogée (saisie lente, interface obsolète)",
      scheduleManagement: "ADE Campus ou Hyperplanning",
      studentComm: "Mails institutionnels + ENT (peu consulté)",
      primaryGoals: "Moderniser l'expérience étudiante, dématérialiser les inscriptions, améliorer le suivi pédagogique",
      mustHave: "Gestion inscriptions, emploi du temps, notes, stages, communication étudiante",
      teachingPhilosophy: "Excellence académique, autonomie de l'étudiant, recherche et innovation",
      challenges: "Budget contraint, résistance au changement, hétérogénéité des profils étudiants"
    }
  },
  {
    id: "ecole-commerce",
    label: "École de Commerce",
    emoji: "💼",
    description: "Business school privée, orientation professionnelle, réseau entreprises fort",
    data: {
      type: "École de commerce privée",
      country: "France",
      totalStudents: "2500",
      totalTeachers: "120",
      totalAdminStaff: "80",
      campusCount: "2",
      departments: "Marketing, Finance, Management, Commerce International, Digital",
      degreeLevels: "Bachelor, Master/MBA, Mastère Spécialisé",
      teachingModality: "Présentiel + e-learning + projets terrain + alternance",
      gradingSystem: "Notes /20, ECTS, évaluations continues + projets",
      teachingLanguages: "Français et Anglais (50/50 en Master)",
      alternancePercent: "60%",
      internationalPercent: "25%",
      internshipRequired: "Oui (stages + alternance obligatoires)",
      researchActivity: "Modérée - chaires de recherche appliquée",
      currentSoftware: "Ypareo ou Hyperplanning",
      currentPainPoints: "Interface datée, pas d'app mobile, émargement instable, suivi alternance complexe",
      attendanceMethod: "Émargement numérique (tablette en classe)",
      gradeManagement: "Saisie manuelle sur logiciel de gestion",
      scheduleManagement: "Hyperplanning ou EDT intégré",
      studentComm: "App école + email + Teams/Slack",
      primaryGoals: "Expérience étudiante premium, suivi alternance fluide, reporting qualité pour certifications",
      mustHave: "Émargement fiable, suivi alternance, portail entreprises, planning temps réel",
      teachingPhilosophy: "Pédagogie par projets, cas réels, intervenants professionnels, international",
      challenges: "Concurrence forte, exigences certifications (AACSB, Equis), satisfaction étudiante clé"
    }
  },
  {
    id: "iut-bts",
    label: "IUT / BTS",
    emoji: "🔧",
    description: "Formation courte professionnalisante, suivi rapproché, stages intégrés",
    data: {
      type: "IUT / Lycée BTS",
      country: "France",
      totalStudents: "800",
      totalTeachers: "60",
      totalAdminStaff: "25",
      campusCount: "1",
      departments: "GEA, TC, Informatique, MMI, ou Sections BTS (MCO, NDRC, CG, SIO...)",
      degreeLevels: "BUT (Bac+3) ou BTS (Bac+2)",
      teachingModality: "Présentiel obligatoire + projets tuteurés + stages",
      gradingSystem: "Notes /20, coefficients, passage par semestre, CCF pour BTS",
      teachingLanguages: "Français",
      alternancePercent: "40%",
      internationalPercent: "5%",
      internshipRequired: "Oui (stages + alternance possibles)",
      researchActivity: "Faible - orienté professionnel",
      currentSoftware: "Pronote, Ypareo ou Sconet",
      currentPainPoints: "Outils multiples non connectés, suivi absences laborieux, communication parents/étudiants",
      attendanceMethod: "Appel en classe + saisie Pronote/Ypareo",
      gradeManagement: "Pronote ou logiciel académique",
      scheduleManagement: "EDT centralisé par la vie scolaire",
      studentComm: "Pronote messagerie + email",
      primaryGoals: "Suivi rapproché des étudiants, gestion absences stricte, lien entreprises alternance",
      mustHave: "Suivi absences temps réel, gestion stages, communication parents, bulletins automatiques",
      teachingPhilosophy: "Encadrement rapproché, professionnalisation, insertion professionnelle rapide",
      challenges: "Public hétérogène, décrochage scolaire, manque d'autonomie des étudiants"
    }
  },
  {
    id: "ecole-ingenieur",
    label: "École d'Ingénieurs",
    emoji: "⚙️",
    description: "Formation scientifique et technique de haut niveau, projets de recherche",
    data: {
      type: "École d'ingénieurs",
      country: "France",
      totalStudents: "1500",
      totalTeachers: "150",
      totalAdminStaff: "60",
      campusCount: "1",
      departments: "Informatique, Mécanique, Génie Civil, Électronique, Mathématiques Appliquées",
      degreeLevels: "Cycle préparatoire, Cycle ingénieur (Bac+5), Doctorat",
      teachingModality: "Cours magistraux + TD + TP labo + projets de fin d'études",
      gradingSystem: "Notes /20, ECTS, classement promotion, jury de passage",
      teachingLanguages: "Français + Anglais technique obligatoire (B2/C1)",
      alternancePercent: "30%",
      internationalPercent: "20%",
      internshipRequired: "Oui (stage ouvrier, stage ingénieur, PFE)",
      researchActivity: "Très active - laboratoires partenaires, thèses CIFRE",
      currentSoftware: "Apogée + Moodle + outils maison",
      currentPainPoints: "Systèmes fragmentés, pas de suivi projet intégré, gestion labo complexe",
      attendanceMethod: "Badge électronique + contrôle en TD/TP",
      gradeManagement: "Apogée ou système maison",
      scheduleManagement: "ADE Campus",
      studentComm: "Intranet + mailing lists + Discord (informel)",
      primaryGoals: "Intégrer suivi projets/stages, moderniser la plateforme, améliorer l'expérience labo",
      mustHave: "Gestion projets PFE, suivi stages multiniveaux, intégration labo, planning complexe",
      teachingPhilosophy: "Rigueur scientifique, approche par projets, recherche appliquée, ouverture internationale",
      challenges: "Complexité des emplois du temps, double cursus, habilitations CTI"
    }
  },
  {
    id: "ecole-art",
    label: "École d'Art & Design",
    emoji: "🎨",
    description: "Formation créative, portfolio-centric, jurys et expositions",
    data: {
      type: "École d'art et de design",
      country: "France",
      totalStudents: "500",
      totalTeachers: "40",
      totalAdminStaff: "15",
      campusCount: "1",
      departments: "Design Graphique, Design Produit, Animation, Architecture Intérieure, Mode",
      degreeLevels: "DNA (Bac+3), DNSEP (Bac+5), post-diplôme",
      teachingModality: "Ateliers + workshop + projets individuels + résidences",
      gradingSystem: "Jurys de passage, évaluations portfolio, crédits ECTS",
      teachingLanguages: "Français",
      alternancePercent: "10%",
      internationalPercent: "15%",
      internshipRequired: "Oui (stages + expositions)",
      researchActivity: "Recherche-création, résidences artistiques",
      currentSoftware: "Système minimal (tableurs + email)",
      currentPainPoints: "Pas de suivi portfolio intégré, communication informelle, gestion ateliers manuelle",
      attendanceMethod: "Feuilles de présence papier",
      gradeManagement: "Jurys avec fiches papier ou tableur",
      scheduleManagement: "Planning affiché + email",
      studentComm: "Email + réseaux sociaux informels",
      primaryGoals: "Portfolio numérique intégré, gestion ateliers/matériel, communication centralisée",
      mustHave: "Suivi portfolio, gestion réservation ateliers, communication jury, calendrier expo",
      teachingPhilosophy: "Créativité individuelle, mentorat, expérimentation, transdisciplinarité",
      challenges: "Profils très variés, évaluation subjective, matériel/espaces partagés"
    }
  }
];
